// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/resources": {
    params: {};
  };
  "/trains": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/resources" | "/trains";
  };
  "dashboard/Dashboard.tsx": {
    id: "dashboard/Dashboard";
    page: "/";
  };
  "ResourceManager.tsx": {
    id: "ResourceManager";
    page: "/resources";
  };
  "TrainManager.tsx": {
    id: "TrainManager";
    page: "/trains";
  };
};